line_length:
    warning: 400
    error: 500
    ignores_comments: true
    ignores_urls: true
type_name:
    excluded:
        pokeDexApp
disabled_rules:
        - trailing_whitespace
        - colon
        - multiple_closures_with_trailing_closure
